apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-mario-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # Define the environments
          - env: dev
          - env: qa
          - env: staging
    - git:
        repoURL: https://github.com/gtkemal/argocd-apps.git
        revision: HEAD
        directories:
          - path: helms/*
  template:
    metadata:
      namespace: argocd
      name: '{{path.basename}}-{{env}}'  # Valid application name: e.g., mario-dev
    spec:
      project: default
      source:
        repoURL: https://github.com/gtkemal/argocd-apps.git
        targetRevision: HEAD
        path: '{{path}}'  # Path to the Helm chart
        helm:
          valueFiles:
            - 'helms/{{path.basename}}/{{env}}-values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'  # Namespace corresponds to the environment
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
