apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-mario-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gtkemal/argocd-apps.git
        revision: HEAD
        directories:
          # Generate an application for each app (nginx, mario)
          - path: helms/*
    - list:
        elements:
          - env: dev
          - env: qa
          - env: staging
  template:
    metadata:
      namespace: argocd
      name: '{{path.basename}}-{{env}}'  # Application name (e.g., nginx-dev, mario-qa)
    spec:
      project: default
      source:
        repoURL: https://github.com/gtkemal/argocd-apps.git
        targetRevision: HEAD
        path: '{{path}}'  # Path to the Helm chart
        helm:
          valueFiles:
            # Reference environment-specific values.yaml
            - 'helms/{{path.basename}}/{{env}}-values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'  # Namespace corresponds to the environment (dev, qa, staging)
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
