apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-mario-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: nginx-dev
            app: nginx
            env: dev
            values: helms/nginx/dev-values.yaml
          - name: mario-dev
            app: mario
            env: dev
            values: helms/mario/dev-values.yaml
          - name: nginx-qa
            app: nginx
            env: qa
            values: helms/nginx/qa-values.yaml
          - name: mario-qa
            app: mario
            env: qa
            values: helms/mario/qa-values.yaml
  template:
    metadata:
      namespace: argocd
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/gtkemal/argocd-apps.git
        targetRevision: HEAD
        path: helms/{{app}}
        helm:
          valueFiles:
            - '{{values}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
