apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-nginx-mario-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: nginx-dev
            app: nginx
            values: helms/nginx/dev-values.yaml
          - name: mario-dev
            app: mario
            values: helms/mario/dev-values.yaml
  template:
    metadata:
      namespace: argocd
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/your-repo.git
        targetRevision: HEAD
        path: helms/{{app}}
        helm:
          valueFiles:
            - '{{values}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
