apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-nginx-mario-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gtkemal/argocd-apps.git
        revision: HEAD
        directories:
          # Generate an application for each subdirectory under helms/
          - path: helms/*
  template:
    metadata:
      namespace: argocd
      name: '{{path.basename}}-dev'  # Application name: e.g., nginx-dev, mario-dev
    spec:
      project: default
      source:
        repoURL: https://github.com/gtkemal/argocd-apps.git
        targetRevision: HEAD
        path: '{{path}}'  # Path to the Helm chart in the repository
        helm:
          valueFiles:
            # Correct reference to dev-values.yaml
            - './dev-values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev  # Deploy to the dev namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
