apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-mario-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gtkemal/argocd-apps.git
        revision: HEAD
        directories:
          # Generate an application for each subdirectory under helms/
          - path: helms/*
  template:
    metadata:
      namespace: argocd
      name: '{{path.basename}}-app'  # Use the directory name (nginx/mario) as the application name
    spec:
      project: default
      source:
        repoURL: https://github.com/gtkemal/argocd-apps.git
        targetRevision: HEAD
        path: '{{path}}'  # Path to the Helm chart in the repository
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'  # Deploy to the namespace matching the chart name
      syncPolicy:
        automated:
          prune: true
          selfHeal: true