envName: dev
spec:
  source:
    targetRevision: HEAD  # Define targetRevision here
  repoURL: https://github.com/gtkemal/argocd-apps.git
  namespace: dev
  project: default
  valueFile: "values.yaml"
  elements:
    - cluster: cluster
      url:https://kubernetes.default.svc

services:
  nginx:
    enabled: true
    path: "helms/nginx"
  mario:
    enabled: false
    path: "helms/mario"
