spec:
  valueFile: dev-values.yaml
  env: dev
  project: default
  namespace: default
  repoURL: https://github.com/gtkemal/argocd-apps.git
  source:
    targetRevision: HEAD
  elements:
    - cluster: cluster
      url: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

services:
  nginx:
    enabled: true
    path: "helms/nginx"
  mario:
    enabled: false
    path: "helms/mario"
