envName: dev
spec:
  env: dev
  namespace: dev
  project: default
  repoURL: https://github.com/gtkemal/argocd-apps.git
  targetRevision: HEAD
  valueFile: "values.yaml"
  elements:
    - cluster: cluster1
      url: https://kubernetes.cluster1.local

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
services:
  nginx:
    enabled: true
    path: "helms/nginx"
  mario:
    enabled: true
    path: "helms/mario"

