apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mario
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gtkemal/argocd-apps.git
    targetRevision: HEAD
    path: ./helms/mario
    helm:
      values: |
        service:
          type: NodePort
          port: 8080
          nodePort: 8600
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
