apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-services-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: nginx
            env: dev
  template:
    metadata:
      name: nginx-dev
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/argocd-apps.git
        targetRevision: HEAD
        path: helms/nginx
        helm:
          valueFiles:
            - helms/nginx/dev-values.yaml
      destination:
        namespace: dev
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
