{{- $targetRevision := $.Values.spec.source.targetRevision -}}

{{- range $key,$val := .Values.services }}

{{- /*
in order to use tpl within a range, _and_ have the key/val available to sub-templates,
need to add some variables to the root context.
*/ -}}

{{- $_ := set $ "curAppName" (print $.Values.envName "-" $key) }}

{{- if $val.enabled }}
---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $.Values.spec.env }}-{{ $key }}
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        {{- range $.Values.spec.elements}}
          - cluster: {{ .cluster  }}
            url: {{ .url  }}
        {{- end }}
  template:
    metadata:
      name: '{{ $.Values.spec.env }}-{{`{{cluster}}`}}-{{ $key }}'
    spec:
      destination:
        namespace: {{ $.Values.spec.namespace }}
        server: '{{`{{url}}`}}'
      project: {{ $.Values.spec.project }}
      source:
        repoURL: {{ $.Values.spec.repoURL }}
        path: {{ $val.path  }}
        targetRevision: {{ $targetRevision }}
        helm:
          valueFiles:
          - "{{ $.Values.spec.valueFile }}"

    {{- if $.Values.spec.syncPolicy }}
      syncPolicy: {{ toYaml $.Values.spec.syncPolicy | nindent 8 }}
  
{{- end }}
{{- end }}
{{- end }}
